services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: otpbank_web
    ports:
      - "80:80"
    volumes:
      - ./otpbank-web:/usr/share/nginx/html:ro
    restart: unless-stopped
