const express = require('express');
const { healthRoutes } = require('./healthRoutes');
const { authRoutes } = require('./authRoutes');
const { userRoutes } = require('./userRoutes');
const { usersRoutes } = require('./usersRoutes');
const { accountsRoutes } = require('./accountsRoutes');
const { cardsRoutes } = require('./cardsRoutes');
const { widgetsRoutes } = require('./widgetsRoutes');
const { productsRoutes } = require('./productsRoutes');
const { scenariosRoutes } = require('./scenariosRoutes');
const { goalsRoutes } = require('./goalsRoutes');
const { investmentsRoutes } = require('./investmentsRoutes');
const { transactionsRoutes } = require('./transactionsRoutes');
const { chatRoutes } = require('./chatRoutes');
const { paymentsRoutes } = require('./paymentsRoutes');
const { storiesRoutes } = require('./storiesRoutes');
const { bonusesRoutes } = require('./bonusesRoutes');
const { notificationsRoutes } = require('./notificationsRoutes');
const { categoriesRoutes } = require('./categoriesRoutes');
const { propertiesRoutes } = require('./propertiesRoutes');
const { vehiclesRoutes } = require('./vehiclesRoutes');
const { autopaymentsRoutes } = require('./autopaymentsRoutes');

const router = express.Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/user', userRoutes);
router.use('/users', usersRoutes);
router.use('/accounts', accountsRoutes);
router.use('/cards', cardsRoutes);
router.use('/widgets', widgetsRoutes);
router.use('/products', productsRoutes);
router.use('/scenarios', scenariosRoutes);
router.use('/goals', goalsRoutes);
router.use('/investments', investmentsRoutes);
router.use('/transactions', transactionsRoutes);
router.use('/chat', chatRoutes);
router.use('/payments', paymentsRoutes);
router.use('/stories', storiesRoutes);
router.use('/bonuses', bonusesRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/categories', categoriesRoutes);
router.use('/properties', propertiesRoutes);
router.use('/vehicles', vehiclesRoutes);
router.use('/autopayments', autopaymentsRoutes);

module.exports = { router };
